include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - build/**
    - lib/generated/**
  
  errors:
    # Errors that stop CI
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    todo: ignore  # TODO comments don't stop build
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Code style
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    
    # Code organization
    - always_use_package_imports
    - avoid_relative_lib_imports
    - sort_constructors_first
    - sort_unnamed_constructors_first
    
    # Security
    - avoid_print
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    
    # Testing
    - test_types_in_equals
    - prefer_asserts_in_initializer_lists
